plugins {
    id 'eclipse'
    id 'idea'
    id 'com.modrinth.minotaur' version '2.8.2'
    id 'net.neoforged.moddev' version '2.0.72'
}

group = "team.creative" + project.mod_id

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

//project.evaluationDependsOn(":CreativeCore")

neoForge {
    version = "21.5.0-beta"
    runs {
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        cmdcam {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
    maven {
        name = "NeoForged"
        url = "https://maven.neoforged.net/releases"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
}

dependencies {
    implementation "maven.modrinth:creativecore:${creativecore_version}"
}
